@startuml
skinparam defaultFontName 宋体
title 相机曝光和帧处理流程

interface Camera{
  +setPreviewSize(width:int,height:int)
  +setPreviewFpsRange(min:int,max:int)
  +setDisplayOrientation(degrees:int)
  +setPreviewCallbackWithBuffer(callback:PreviewCallback)
  +addCallbackBuffer(buffer:byte[])
  +setParameters(parameters:Camera.Parameters)
  +startPreview()
  +stopPreview()
}

@enduml